with-expecter: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
dir: "gen/go/mocks/{{ .PackageName }}"
mockname: "{{ .Mock }}{{ .InterfaceName }}"
outpkg: "{{ .PackageName }}"
inpackage: false
unroll-variadic: false # https://vektra.github.io/mockery/latest/notes/#variadic-arguments

packages:
  github.com/webitel/engine/auth_manager:
    config:
      dir: "gen/go/mocks/{{ .InterfaceDirRelative }}"
    interfaces:
      AuthManager:
  github.com/webitel/webitel-wfm/infra/storage/dbsql/cluster:
    interfaces:
      Database:
      Queryer:
  github.com/webitel/webitel-wfm/internal/handler:
    interfaces:
      PauseTemplateManager:
      ShiftTemplateManager:
      WorkingConditionManager:
      AgentWorkingConditionsManager:
      AgentAbsenceManager:
      WorkingScheduleService:
  github.com/webitel/webitel-wfm/internal/service:
    interfaces:
      PauseTemplateManager:
      ShiftTemplateManager:
      WorkingConditionManager:
      AgentWorkingConditionsManager:
      AgentAbsenceManager:
