with-expecter: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
dir: "gen/go/mocks/{{ .PackageName }}"
mockname: "{{ .Mock }}{{ .InterfaceName }}"
outpkg: "{{ .PackageName }}"
inpackage: false
unroll-variadic: false # https://vektra.github.io/mockery/latest/notes/#variadic-arguments

packages:
  github.com/webitel/webitel-wfm/infra/health:
    interfaces:
      Check:
  github.com/webitel/webitel-wfm/infra/webitel/auth:
    interfaces:
      Manager:
  github.com/webitel/webitel-wfm/infra/storage/dbsql:
    interfaces:
      Database:
  github.com/webitel/webitel-wfm/internal/handler:
    interfaces:
      PauseTemplateManager:
      ShiftTemplateManager:
      WorkingConditionManager:
      AgentWorkingConditionsManager:
      AgentAbsenceManager:
      WorkingScheduleService:
  github.com/webitel/webitel-wfm/internal/service:
    interfaces:
      PauseTemplateManager:
      ShiftTemplateManager:
      WorkingConditionManager:
      AgentWorkingConditionsManager:
      AgentAbsenceManager:
