inputs:
  host:
    required: true
    description: "Remote host (IP or domain) where the build artifacts will be deployed"

  user:
    required: true
    description: "SSH username used to connect to the remote host"

  private-key:
    required: true
    description: "Private SSH key used for authentication with the remote host"

  source:
    required: true
    description: "Build artifact (e.g., .deb package) to be copied and installed on the remote host"

  service:
    required: true
    description: "Systemd service to restart after the package is installed"

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-packages

    - name: Copy build
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.private-key }}
        source: ${{ inputs.source }}
        target: ~/dist

    - name: Install
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.private-key }}
        script: |
          sudo dpkg -i ~/dist/${{ inputs.source }}
          rm ~/dist/${{ inputs.source }}
          sudo systemctl restart ${{ inputs.service }}