inputs:
  host:
    required: true
    description: ""

  private-key:
    required: true
    description: ""

  source-name:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-packages

    - name: Copy build
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: admin
        key: ${{ inputs.private-key }}
        source: ${{ inputs.source-name }}
        target: ~/dist

    - name: Install
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.host }}
        username: admin
        key: ${{ inputs.private-key }}
        script: |
          sudo dpkg -i ~/dist/${{ inputs.source-name }}
          rm ~/dist/${{ inputs.source-name }}