runs:
  using: "composite"
  steps:
    - name: Download generated code (Go)
      uses: actions/download-artifact@v4
      with:
        name: generated-code-go
        path: gen/go

    - name: Download generated code (wire)
      uses: actions/download-artifact@v4
      with:
        name: generated-code-wire
        path: cmd/