inputs:
  aws-secret-id:
    required: true
    description: "AWS access key ID used for authentication to S3"

  aws-secret-key:
    required: true
    description: "AWS secret access key used for authentication to S3"

  aws-bucket-region:
    required: true
    description: "AWS region where the S3 bucket is located (e.g., us-east-1)"

  aws-bucket-name:
    required: true
    description: "Name of the S3 bucket where the package will be uploaded"

  source:
    required: true
    description: "Build artifact (e.g., .deb package) that will be uploaded to the S3 bucket"

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-packages

    - name: Publish packages
      shell: bash
      env:
        SOURCE_NAME: ${{ inputs.source }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-secret-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-bucket-region }}
        AWS_BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      run: |
        deb-s3 upload ${SOURCE_NAME} \
          --visibility nil \
          --bucket "${AWS_BUCKET_NAME}" \
          --s3-region "${AWS_DEFAULT_REGION}" \
          --arch amd64 \
          --component dev \
          --codename bookworm 
