inputs:
  aws-secret-id:
    required: true
    description: ""

  aws-secret-key:
    required: true
    description: ""

  aws-bucket-region:
    required: true
    description: ""

  aws-bucket-name:
    required: true
    description: ""

  source-name:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.1'

    - name: Install deb-s3
      shell: bash
      run: gem install deb-s3

    - name: Publish packages
      shell: bash
      env:
        SOURCE_NAME: ${{ inputs.source-name }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-secret-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-bucket-region }}
        AWS_BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      run: |
        deb-s3 upload ${SOURCE_NAME} \
          --visibility nil \
          --bucket "${AWS_BUCKET_NAME}" \
          --s3-region "${AWS_DEFAULT_REGION}" \
          --arch amd64 \
          --component dev \
          --codename bookworm 
