runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.1'

    - name: Install deb-s3
      shell: bash
      run: gem install deb-s3

    - name: Publish packages
      shell: bash
      run: echo "Publish package to S3!"