name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build snapshot
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: "Set up buf.build"
        uses: bufbuild/buf-setup-action@v1

      - name: "Build snapshot using goreleaser/goreleaser-action"
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}