name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: webitel/webitel-wfm/.github/workflows/test.yml@main

  build:
    name: Build snapshot
    runs-on: ubuntu-latest
      - name: Build snapshot using goreleaser/goreleaser-action
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}