name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    uses: webitel/webitel-wfm/.github/workflows/test.yml@main

  build:
    name: Snapshot
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for the changelog to work correctly.

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Install Go tools
        run: go install tool

      - name: Generating code
        run: go generate

      - name: Build snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.3.2
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}