on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  deploy-dev:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy artifact
        uses: ./.github/actions/deploy-build

  # Request approves for build
  # Install .deb pkg from artifact
  deploy-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Noop
        run: echo "Deploy build to test environment!"

  # Request approves for build
  # Publish pkg to repository
  # Install .deb pkg via apt
  deploy-stage:
    needs: [ deploy-test ]
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Noop
        run: echo "Deploy build to stage environment!"