name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  deploy-dev:
    needs: [ build ]
    runs-on:
      - arc-runner-set
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb

  # Request approves for build
  # Install .deb pkg from artifact
  deploy-test:
    needs: [ build, deploy-dev ]
    runs-on:
      - arc-runner-set
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb

  # Request approves for build
  # Publish pkg to repository
  # Install .deb pkg via apt
  deploy-stage:
    needs: [ deploy-test ]
    runs-on:
      - arc-runner-set
    environment: stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb

      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source-name: webitel-wfm-*.deb
          aws-bucket-name: webitel-deb-pkg
          aws-bucket-region: us-east-2
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
