on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  deploy-dev:
    needs: [ build ]
    runs-on:
      - codebuild-wfm-${{ github.run_id }}-${{ github.run_attempt }}
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb

  # Request approves for build
  # Install .deb pkg from artifact
  deploy-test:
    needs: [ build ]
    runs-on:
      - codebuild-wfm-${{ github.run_id }}-${{ github.run_attempt }}
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb

  # Request approves for build
  # Publish pkg to repository
  # Install .deb pkg via apt
  deploy-stage:
    needs: [ deploy-test ]
    runs-on:
      - codebuild-wfm-${{ github.run_id }}-${{ github.run_attempt }}
    environment: stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-name: webitel-wfm-*.deb