name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  dev:
    name: Deploy / Development
    needs: [ build ]
    runs-on: [ arc-runner-set ]
    environment: dev
    steps:
      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: ''
          user: ''

  # Request approves for build
  # Install .deb pkg from artifact
  test:
    name: Deploy / Testing
    needs: [ build, dev ]
    runs-on: [ arc-runner-set ]
    environment: test
    steps:
      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: ''
          user: ''

  repository:
    name: Publish .deb package
    needs: [ build, test ]
    runs-on: [ arc-runner-set ]
    steps:
      - name: Noop
        run: echo "Upload release to repository!"