name: Deploy

on:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/ci-checks.yml

  compile:
    name: Compile application
    needs: [ checks ]
    runs-on: [ arc-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for the changelog to work correctly

      - name: Download generated code
        uses: ./.github/actions/download-generated
        with:
          wire: true

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ needs.version.outputs.version }}
        run: goreleaser release --clean --skip publish --skip validate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-packages
          compression-level: 9
          path: dist/webitel-wfm-*.*

  # Install .deb pkg from artifact
  development:
    name: Development
    needs: [ compile ]
    runs-on: [ arc-runner-set ]
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          user: ${{ secrets.SSH_USER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  # Request approves for build
  # Install .deb pkg from artifact
  testing:
    name: Testing
    needs: [ compile, development ]
    runs-on: [ arc-runner-set ]
    environment: testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ secrets.TESTING_HOST }}
          user: ${{ secrets.SSH_USER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  repository:
    name: Publish .deb package
    needs: [ compile, testing ]
    runs-on: [ arc-runner-set ]
    environment: acceptance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source: webitel-wfm-*.deb
          aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
          aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          component: ${{ needs.build.outputs.component }}
          codename: ${{ vars.DEB_CODENAME }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}