name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  development:
    name: Development
    needs: [ build ]
    runs-on: [ arc-runner-set ]
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          user: development
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  # Request approves for build
  # Install .deb pkg from artifact
  testing:
    name: Testing
    needs: [ build, development ]
    runs-on: [ arc-runner-set ]
    environment: testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          user: development
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  repository:
    name: Publish .deb package
    needs: [ build, testing ]
    runs-on: [ arc-runner-set ]
    environment: acceptance
    steps:
      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source: webitel-wfm-*.deb
          aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
          aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          component: ${{ needs.build.outputs.component }}
          codename: ${{ vars.DEB_CODENAME }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}