name: Development

on:
  push:
    branches:
      - main

env:
  SYSTEMD_SERVICE_NAME: webitel-wfm
  PACKAGE_PATTERN: webitel-wfm-*.deb

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/0-prepare.yml
    with:
      wire: true

  checks:
    name: Checks
    needs: [ prepare ]
    uses: ./.github/workflows/1-checks.yml

  compile:
    name: Build
    needs: [ prepare ]
    uses: ./.github/workflows/2-build.yml
    with:
      source: ${{ env.PACKAGE_PATTERN }}
      version: ${{ needs.version.outputs.version }}

  development:
    name: Development
    needs: [ compile ]
    uses: ./.github/workflows/3-deploy.yml
    secrets:
      host: ${{ secrets.DEVELOPMENT_HOST }}
      user: ${{ secrets.SSH_USER }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      environment: development
      service: ${{ env.SYSTEMD_SERVICE_NAME }}
      source: ${{ env.PACKAGE_PATTERN }}

  testing:
    name: Testing
    needs: [ compile ]
    uses: ./.github/workflows/3-deploy.yml
    secrets:
      host: ${{ secrets.TESTING_HOST }}
      user: ${{ secrets.SSH_USER }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      environment: testing
      service: ${{ env.SYSTEMD_SERVICE_NAME }}
      source: ${{ env.PACKAGE_PATTERN }}

  repository:
    name: Publish .deb package
    needs: [ compile, testing ]
    runs-on: [ arc-runner-set ]
    environment: acceptance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source: ${{ env.PACKAGE_PATTERN }}
          aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
          aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          component: ${{ needs.build.outputs.component }}
          codename: ${{ vars.DEB_CODENAME }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}