name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  # Install .deb pkg from artifact
  development:
    name: Deploy / Development
    needs: [ build ]
    runs-on: [ arc-runner-set ]
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          user: development
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  # Request approves for build
  # Install .deb pkg from artifact
  testing:
    name: Deploy / Testing
    needs: [ build, development ]
    runs-on: [ arc-runner-set ]
    environment: testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy artifact
        uses: ./.github/actions/deploy-build
        with:
          host: ${{ vars.HOST_IP }}
          user: development
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: webitel-wfm-*.deb
          service: webitel-wfm

  repository:
    name: Publish .deb package
    needs: [ build, testing ]
    runs-on: [ arc-runner-set ]
    steps:
      - name: Noop
        run: echo "Upload release to repository!"