name: Development

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/0-prepare.yml
    with:
      wire: true
      package-pattern: webitel-wfm-*.deb
      systemd-service: webitel-wfm

  checks:
    name: Checks
    needs: [ prepare ]
    uses: ./.github/workflows/1-checks.yml
    with:
      wire: true

  compile:
    name: Build
    needs: [ prepare ]
    uses: ./.github/workflows/2-build.yml
    with:
      wire: true
      source: ${{ needs.prepare.outputs.package-pattern }}
      version: ${{ needs.prepare.outputs.version }}

  development:
    name: Development
    needs: [ prepare, compile ]
    uses: ./.github/workflows/3-deploy.yml
    secrets:
      host: ${{ secrets.DEVELOPMENT_HOST }}
      user: ${{ secrets.SSH_USER }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      environment: development
      service: ${{ needs.prepare.outputs.systemd-service }}
      source: ${{ needs.prepare.outputs.package-pattern }}

  testing:
    name: Testing
    needs: [ prepare, compile, development ]
    uses: ./.github/workflows/3-deploy.yml
    secrets:
      host: ${{ secrets.TESTING_HOST }}
      user: ${{ secrets.SSH_USER }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      environment: testing
      service: ${{ needs.prepare.outputs.systemd-service }}
      source: ${{ needs.prepare.outputs.package-pattern }}

  repository:
    name: Publish .deb package
    needs: [ prepare, compile, testing ]
    runs-on: [ arc-runner-set ]
    environment: acceptance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source: ${{ needs.prepare.outputs.package-pattern }}
          aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
          aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          component: ${{ needs.build.outputs.component }}
          codename: ${{ vars.DEB_CODENAME }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}