on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Go (version from go.mod)
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download generated code (Go)
        uses: actions/download-artifact@v4
        with:
          name: generated-code-go
          path: gen/go

      - name: Download generated code (wire)
        uses: actions/download-artifact@v4
        with:
          name: generated-code-wire
          path: cmd/

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.2
        with:
          version: v1.64.7
