name: prepare

on:
  workflow_call:
    outputs:
      version:
        description: 'Extracted version'
        value: ${{ steps.version.outputs.version }}

      component:
        description: 'Extracted component'
        value: ${{ jobs.version.outputs.component }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse-version.outputs.WEBITEL_VERSION }}
      component: ${{ steps.parse-version.outputs.WEBITEL_DEB_COMPONENT }}
    steps:
      - name: Parse version
        id: version
        uses: ./.github/actions/parse-version
        with:
          version-env-name: WEBITEL_VERSION
          component-env-name: WEBITEL_DEB_COMPONENT

  dependencies:
    runs-on:
      - arc-runner-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-code-go
          compression-level: 9
          path: gen/go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-code-wire
          compression-level: 9
          path: cmd/wire_gen.go