name: Checks

on:
  pull_request:
    branches: [ main ]

  workflow_call:


jobs:
  lint:
    name: Lint code
    needs: [ dependencies ]
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download generated code
        uses: ./.github/actions/download-generated
        with:
          wire: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.2
        with:
          install-mode: none
          problem-matchers: true
          skip-cache: true

  govulncheck:
    name: Check vulnerabilities
    needs: [ dependencies ]
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download generated code
        uses: ./.github/actions/download-generated
        with:
          wire: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck and save to file
        run: govulncheck -C . -format sarif ./... > report.sarif

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: report.sarif

  test:
    name: Unit testing
    needs: [ dependencies ]
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download generated code
        uses: ./.github/actions/download-generated
        with:
          wire: true

      - name: Run all tests
        run: go test -short -v ./... | go run github.com/jstemmer/go-junit-report@latest -set-exit-code > report.xml

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.4
        with:
          paths: report.xml
