name: Release

on:
  push:
    branches:
      - v*.* # Only release branches

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/0-prepare.yml
    with:
      wire: true
      package-pattern: webitel-wfm-*.deb
      systemd-service: webitel-wfm

  compile:
    name: Build
    needs: [ prepare ]
    uses: ./.github/workflows/2-build.yml
    with:
      wire: true
      source: ${{ needs.prepare.outputs.package-pattern }}
      version: ${{ needs.prepare.outputs.version }}

  repository:
    name: Publish .deb package
    needs: [ prepare, compile ]
    runs-on: [ arc-runner-set ]
    environment:
      name: ${{ needs.prepare.outputs.component }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Publish build
        uses: ./.github/actions/upload-s3
        with:
          source: webitel-wfm-*.deb
          aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
          aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          component: ${{ needs.prepare.outputs.component }}
          codename: ${{ vars.DEB_CODENAME }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}

  staging:
    name: Staging
    needs: [ prepare, compile ]
    uses: ./.github/workflows/3-deploy.yml
    secrets:
      host: ${{ secrets.STAGING_HOST }}
      user: ${{ secrets.SSH_USER }}
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    with:
      environment: staging
      service: ${{ needs.prepare.outputs.systemd-service }}
      source: ${{ needs.prepare.outputs.package-pattern }}
