on:
  push:
    branches:
      - v*.* # Only release branches

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # We don't have a prod environment for each release,
  # so assume changes are tested.
  # Upload release to the repository.
  release:
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - name: Noop
        run: echo "Upload release to repository!"

  # If it is the latest release - deploy it to stage environment.
  deploy:
    needs: [ build ]
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Noop
        run: echo "Deploy latest release to prod environment!"