on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
