name: Development1

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: kirychukyurii/reusable-configs/.github/workflows/workflow.yml@364d788b7b5d7799be2a82461bb2314c203f9dd6
    with:
      triggered-branch: '${{ github.ref_name }}'
      development-branch: 'main'