name: Development1

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: kirychukyurii/reusable-configs/.github/workflows/workflow.yml@main
    with:
      triggered-branch: '${{ github.ref_name }}'
      development-branch: 'main'