name: Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    uses: webitel/webitel-wfm/.github/workflows/lint.yml@main

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup buf.build
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.38.0

      - name: Generating code
        run: go generate

      - name: Cache generated code
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gen-${{ hashFiles('**/go.sum') }}
          path: ./gen

      - name: Run tests
        run: go test